### ISSUE TITLE
MySQL Error on Plugin Disable

### ISSUE THREAD

**Issue by B4TT3RY** [egg82/AltFinder#1]
```
[19:22:56 INFO]: [AltFinder] Disabling AltFinder v2.4.18
[19:23:04 INFO]: [me.egg82.altfinder.external.com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown initiated...
[19:23:04 ERROR]: [me.egg82.altfinder.sql.MySQL] HikariDataSource HikariDataSource (HikariPool-1) has been closed.
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
at me.egg82.altfinder.external.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[?:?]
at me.egg82.altfinder.external.ninja.egg82.sql.SQL.query(SQL.java:41) ~[?:?]
at me.egg82.altfinder.sql.MySQL.lambda$fetchQueue$3(MySQL.java:118) ~[?:?]
at me.egg82.altfinder.sql.MySQL$$Lambda$2343.00000000900083B0.get(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_202]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_202]
[19:23:04 ERROR]: [me.egg82.altfinder.sql.MySQL] HikariDataSource HikariDataSource (HikariPool-1) has been closed.
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
at me.egg82.altfinder.external.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[?:?]
at me.egg82.altfinder.external.ninja.egg82.sql.SQL.execute(SQL.java:93) ~[?:?]
at me.egg82.altfinder.sql.MySQL.lambda$fetchQueue$3(MySQL.java:151) ~[?:?]
at me.egg82.altfinder.sql.MySQL$$Lambda$2343.00000000900083B0.get(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_202]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_202]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_202]
[19:23:04 INFO]: [me.egg82.altfinder.external.com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown completed.
[19:23:04 INFO]: [AltFinder] Disabled
```

> Version
> Paper 1.13.2 Build 525

This error sometimes occurs.

**Comment by egg82** [comment]
Thanks for the report! I'll look into it.

**Comment by egg82** [comment]
Should be fixed in latest release
