### ISSUE TITLE
Plugin fails to enable on Waterfall

### ISSUE THREAD

**Issue by Trikolon** [egg82/AltFinder#13]
Plugin version: '3.4.24'
Server type: 'Waterfall #448'
Server version: '1.17.1'
Java Version: '16'

**Describe the bug**
The plugin fails to enable. It shows the following stacktrace:
```
mc-proxy_1        | [07:12:13 INFO]: [AltFinder] Loading dep Caffeine                                                                                                                
mc-proxy_1        | [07:12:13 WARN]: Error loading plugin AltFinder                                                                                                                  
mc-proxy_1        | java.lang.ExceptionInInitializerError: null                                                                                                                      
mc-proxy_1        |     at me.egg82.altfinder.BungeeBootstrap.loadJars(BungeeBootstrap.java:66) ~[?:?]                                                                               
mc-proxy_1        |     at me.egg82.altfinder.BungeeBootstrap.onLoad(BungeeBootstrap.java:33) ~[?:?]                                                                                 
mc-proxy_1        |     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[Waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:
448]                                                                                                                                                                                 
mc-proxy_1        |     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[Waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:4
48]
mc-proxy_1        |     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[Waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
mc-proxy_1        |     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[Waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
mc-proxy_1        |     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
mc-proxy_1        | Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base
 does not "opens java.net" to unnamed module @504e1599
mc-proxy_1        |     at java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source) ~[?:?]
mc-proxy_1        |     at java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source) ~[?:?]
mc-proxy_1        |     at java.lang.reflect.Method.checkCanSetAccessible(Unknown Source) ~[?:?]
mc-proxy_1        |     at java.lang.reflect.Method.setAccessible(Unknown Source) ~[?:?]
mc-proxy_1        |     at me.egg82.altfinder.utils.JarUtil.<clinit>(JarUtil.java:28) ~[?:?]
mc-proxy_1        |     ... 7 more
```

**Expected behavior**

**To Reproduce**
1. Install the plugin
2. Start the server
4. See error (see stacktrace above)

**Comment by Trikolon** [comment]
Update: the issue is also reproducible on 1.18
