### ISSUE TITLE
Altfinder (and antivpn) fail to load on latest waterfall (with the same error)

### ISSUE THREAD

**Issue by PaintsplattersMC** [egg82/AltFinder#14]
Plugin version: '3.4.24'
Server type: 'Waterfall '
Server version: '466'

**Describe the bug**
Alt finder (and antivpn) fail to load with (the same)  an error in console.

**Expected behavior**
The plugin should load and function as it previously did

**To Reproduce**
Update to latest waterfall for 1.18 from 1.17.1 versions.
**Plugins**
![Screenshot from 2021-12-09 15-46-50](https://user-images.githubusercontent.com/83564809/145480907-c5772f52-3ebf-4071-a0b4-3fafccfbb071.png)

**Error** Quite small.
[22:43:20] [main/WARN]: Error loading plugin AltFinder
java.lang.ExceptionInInitializerError: null
	at me.egg82.altfinder.BungeeBootstrap.onLoad(BungeeBootstrap.java:38) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:bf5e3c4:466]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:bf5e3c4:466]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:bf5e3c4:466]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:bf5e3c4:466]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:bf5e3c4:466]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class java.net.URLClassLoader.findClass(java.lang.String) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens java.net" to unnamed module @2ca5f1ed
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at me.egg82.altfinder.external.ninja.egg82.services.ProxiedURLClassLoader.<clinit>(ProxiedURLClassLoader.java:20) ~[?:?]
	... 6 more

**Comment by PaintsplattersMC** [comment]
Update. add java line ```--illegal-access=permit``` and it works

**Comment by Trikolon** [comment]
This is a dupe of https://github.com/egg82/AltFinder/issues/13
